sqlConfig: &sqlConfig
    code: sqldb
    driverName: pgx
    urlAdress: "postgres://chaitu:chaitu@localhost:5432/chaitu"
useCaseConfig:
    task:
        code: task
        taskDataConfig: &taskDataConfig
            code: taskData
            dataStoreConfig: *sqlConfig
        txDataConfig: &txDataConfig
            code: txData
            dataStoreConfig: *sqlConfig
            